services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: lms
      POSTGRES_PASSWORD: lms123
      POSTGRES_DB: library
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

  flask_app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://lms:lms123@db:5432/library
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
